---
name: Bird3
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary packages
        run: |
          sudo apt-get update && sudo apt-get -y install apt-transport-https ca-certificates wget

      - name: Add CZ.NIC Labs Packaging GPG key
        run: |
          sudo wget -O /usr/share/keyrings/cznic-labs-pkg.gpg https://pkg.labs.nic.cz/gpg

      - name: Setup the bird3 repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/bird3 trixie main" | sudo tee /etc/apt/sources.list.d/cznic-labs-bird3.list

      - name: UPdate apt bacpakge index with bird3 repo enabled
        run: |
          sudo apt-get update

      - name: Get latest version from APT
        id: apt
        run: |
          LATEST=$(apt-cache policy "$PKG_NAME" | grep Candidate | awk '{print $2}')
          echo "version=$LATEST" >> $GITHUB_OUTPUT
