---
name: Check and update bird

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  get-apt-version:
    runs-on: ubuntu-latest
    container:
      image: debian:12.11-slim@sha256:2424c1850714a4d94666ec928e24d86de958646737b1d113f5b2207be44d37d8
    outputs:
      app_version: ${{ steps.apt.outputs.app_version }}
      image_version: ${{ steps.apt.outputs.image_version }}
    steps:
      - name: Install necessary packages
        run: |
          apt-get update && apt-get -y install apt-transport-https ca-certificates curl jq

      - name: Add CZ.NIC Labs Packaging GPG key
        run: |
          curl -o /usr/share/keyrings/cznic-labs-pkg.gpg https://pkg.labs.nic.cz/gpg

      - name: Setup the bird repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cznic-labs-pkg.gpg] https://pkg.labs.nic.cz/bird3 bookworm main" | tee /etc/apt/sources.list.d/cznic-labs-bird3.list

      - name: UPdate apt bacpakge index with bird repo enabled
        run: |
          apt-get update

      - name: Get latest version from APT
        id: apt
        run: |
          APP_VERSION=$(apt-cache policy "bird3" | grep Candidate | awk '{print $2}')
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

          IMAGE_VERSION=$(echo "$APP_VERSION" | cut -d'-' -f1)
          echo "image_version=$IMAGE_VERSION" >> $GITHUB_OUTPUT

  check-registry:
    runs-on: ubuntu-latest
    needs: get-apt-version
    outputs:
      outcome: ${{ steps.docker.outcome }}
      conclusion: ${{ steps.docker.conclusion }}

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image version exists in Dockerhub
        id: docker
        continue-on-error: true
        run: |
          IMAGE_VERSION=${{ needs.get-apt-version.outputs.image_version }}
          IMAGE="${{ vars.DOCKER_USERNAME }}/bird:${IMAGE_VERSION}"
          docker manifest inspect "$IMAGE"

  build-and-publish-image:
    # When a continue-on-error step fails, the outcome is failure, but the final conclusion is success.
    if: needs.check-registry.outputs.outcome == 'failure' && needs.check-registry.outputs.conclusion == 'success'
    uses: ./.github/workflows/build-and-publish.yaml
    secrets: inherit
    permissions:
      contents: read
      attestations: write
      id-token: write
    needs:
      - get-apt-version
      - check-registry
    with:
      app_name: bird
      app_version: ${{ needs.get-apt-version.outputs.app_version }}
      image_version: ${{ needs.get-apt-version.outputs.image_version }}
